language: go
sudo: false
go:
- 1.9.2
before_install:
- go get github.com/golang/dep/cmd/dep
- go get github.com/twitchtv/retool
install:
- dep ensure
- retool sync
script:
- go vet ./...
- retool do megacheck ./...
- go test -v -race ./...
- retool do goveralls -service=travis-ci
notifications:
  slack:
    secure: kQeFL4M5bfLcj/QQA1fTqXDDSKM3xZ3rSrw15tgXNE0tTf6O9kZyfbMQSBnpEKoo0B9HRH3NEaOaQgR8Tinymo4DrvCKRYZE1OA4qLg06saPixVELQWQvFu+mQhUFnc2PQbApsz/yPuw4P511uo+SXEjSfVxMOU5he4vd0npcEHJSF7zSo+3YxfQQ4cPU9KLjWk9xA5N+W91VX4+bSEBRFZAzrr9Sp4JqmuEyJOF6yuHvtE0z0BgQFl0URbLpgxDQPGGHL3h/uS2uw2WJ/QlvKJrCw0bBD8Bo6nfx0siLjLfI9hFm2qViXHUJw12FxS/OHTHcVisAgCviXuIj+3j2ThCDpSsCKFuvXrh7ZvqLDitw6acwWV8YLTvV4Rm/yTzPzxHNgqMW+f59FEEFcqJpgv9kTUSiIrB+WOz7HH1sHSvbIJ+9CmqJjOZxTpfKzugphn0YsBrtbGHkRJnWnBukvDb47sCaXCiTnnRLjJTcdXTMsWMo/G+GNrPJUg/Ld7TYyIVW1iuZZFeKprhF7dgeDvCN7yMHyjfvHWINQR66JGQ2l1xPtwmCWWXl2+4VpRnqKxpGbv7kzBTOjWvRCTaHK5SKMBWKB8BtLOKIA0GSyDAbH7BbNm4MdRvj+DDQrAf9M1lNacO814HLdzriuXSzQ9c8ZSgB4TFLxrkDbnmFqA=
  on_success: change
  on_failure: always
env:
  global:
    secure: RJFYKm2gAZG51SmZ2QsMfhyRpuhaNIvxYCvjXk0dX4+m8X4R8eZyMk/zIuW2t7pGBOtXvkR3dWtikBlLfn0lSzp34YZzN6nKxC0yrOh0b01Sn5UcqHFTQwWlIhGxGt4QfFmJTbNSVLviizCfKPdhjKOlZZUp4xMA4RsafV406QhkcDJwnDT/sJMmSJLbD1W9YH+hsQzbqyIhpsqa9lRL6P3N4cWZUBY4mCXr73caGTJHt69XpZ4dWyF9bjz7Od1/Do6rY/nVLtT5gyPe6chZ+xCDlKWnAOBHANzSGzboDZPSCWXvCGEfQuHOCxZBlBOYDR3MtXQPHSYpxZ0sYiVzhNYeFMDg14LM7Jc+pQQ13XojR70Uh9QUD1QOiIHBkaVjku8eoj7zRRxOo1pufSvg2YLpDCmL+DE/pDaCzIfV568qU9kZrjDaiwJS9TNY2lYcO8PvWp08AiFQ6uUWNS2GtVvz3vnzpOg3AFRA7vukAIkH8KnyPctR/DOynU+OkMra8zrdAXbgXlhMgsjXCSessF4t/CiglbL/PMWqnrz2uTBLtj5kWDHn2ddRHy5kbvdsByxDMrf6W8cifQpkQQxW/7plhuioz2OxMqlk6qHvb18qKhXHjpLnAz2hY3qqlvBcdgAdrSXMYBwhK+0sgifWlnY+r4pQFvDt2e6Z0EqCDEk=
