language: go
sudo: false
go:
- 1.9.1
before_install:
- go get github.com/golang/dep/cmd/dep
- go get honnef.co/go/tools/cmd/megacheck
install:
- dep ensure
script:
- go vet ./...
- megacheck ./...
- go test -v -race ./...
notifications:
  slack:
    secure: kQeFL4M5bfLcj/QQA1fTqXDDSKM3xZ3rSrw15tgXNE0tTf6O9kZyfbMQSBnpEKoo0B9HRH3NEaOaQgR8Tinymo4DrvCKRYZE1OA4qLg06saPixVELQWQvFu+mQhUFnc2PQbApsz/yPuw4P511uo+SXEjSfVxMOU5he4vd0npcEHJSF7zSo+3YxfQQ4cPU9KLjWk9xA5N+W91VX4+bSEBRFZAzrr9Sp4JqmuEyJOF6yuHvtE0z0BgQFl0URbLpgxDQPGGHL3h/uS2uw2WJ/QlvKJrCw0bBD8Bo6nfx0siLjLfI9hFm2qViXHUJw12FxS/OHTHcVisAgCviXuIj+3j2ThCDpSsCKFuvXrh7ZvqLDitw6acwWV8YLTvV4Rm/yTzPzxHNgqMW+f59FEEFcqJpgv9kTUSiIrB+WOz7HH1sHSvbIJ+9CmqJjOZxTpfKzugphn0YsBrtbGHkRJnWnBukvDb47sCaXCiTnnRLjJTcdXTMsWMo/G+GNrPJUg/Ld7TYyIVW1iuZZFeKprhF7dgeDvCN7yMHyjfvHWINQR66JGQ2l1xPtwmCWWXl2+4VpRnqKxpGbv7kzBTOjWvRCTaHK5SKMBWKB8BtLOKIA0GSyDAbH7BbNm4MdRvj+DDQrAf9M1lNacO814HLdzriuXSzQ9c8ZSgB4TFLxrkDbnmFqA=
  on_success: change
  on_failure: always
