steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/${PROJECT_ID}/my-scraper || exit 0
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/my-scraper:${SHORT_SHA}', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/${PROJECT_ID}/my-scraper']

- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', 'my-scraper', '--platform', 'managed', '--image', 'gcr.io/$PROJECT_ID}/my-scraper:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated']
