steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - '--destination=gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}'
  - --cache=true

- name: gcr.io/cloud-builders/gcloud
  args: ['beta', 'run', 'deploy', '${REPO_NAME}', '--platform', 'managed', '--image', 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated']
