steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/${PROJECT_ID}/${REPO_NAME}"]

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', '${REPO_NAME}', '--platform', 'managed', '--image', 'gcr.io/$PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}', '--region', 'us-central1', '--allow-unauthenticated']
