
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/ChimeraCoder/anaconda"
  branch = "master"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/feeds"
  branch = "master"

[[constraint]]
  name = "github.com/joho/godotenv"
  branch = "master"

[[constraint]]
  name = "github.com/lestrrat-go/server-starter"
  branch = "master"

[[constraint]]
  name = "github.com/pkg/errors"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  name = "golang.org/x/oauth2"
  branch = "master"

[[constraint]]
  name = "golang.org/x/text"
  branch = "master"

[[constraint]]
  name = "google.golang.org/api"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"
