[tools]
  go = "1.27.0"

[env]
  _.file = ".env"
  GOPROXY = "https://golang.flatt.tech"

[vars]
  testopts = "-v -race ./..."
  buildopts = '-tags netgo,timetzdata -installsuffix netgo -ldflags "-s -extldflags -static"'

[tasks.build]
  run = "go build {{vars.buildopts}}"
  env = { CGO_ENABLED = "0" }

[tasks.dev]
  run = "go tool air"

[tasks.get]
  run = "go get"

[tasks.run]
  run = "go run ."

[tasks."test:mod"]
  run = "go mod verify"

[tasks."test:vet"]
  run = "go vet ./..."

[tasks."test:unit"]
  run = "go tool gotestsum -- {{vars.testopts}}"

[tasks."test:staticcheck"]
  run = "go tool staticcheck ./..."

[tasks.test]
  depends = ["test:*"]

[tasks.upgrade]
  run = [
    "go get -u",
    "go mod tidy",
  ]
