version: "3"

dotenv: [".env"]

vars:
  TESTOPTS: -v -race ./...
  BUILDOPTS: -tags netgo,timetzdata -installsuffix netgo -ldflags "-w -s -extldflags -static"

tasks:
  build:
    cmds:
      - go build {{.BUILDOPTS}} {{.CLI_ARGS}}
    env:
      CGO_ENABLED: 0

  get:
    cmds:
      - go get

  run:
    cmds:
      - go run .

  test:
    cmds:
      - go mod verify
      - go vet ./...
      - go run gotest.tools/gotestsum -- {{.TESTOPTS}}
      - go run honnef.co/go/tools/cmd/staticcheck ./...

  watch:
    cmds:
      - go run github.com/air-verse/air {{.CLI_ARGS}}

  upgrade:
    cmds:
      - go get -u
      - go mod tidy
